name: Run Quotex Bot 24/7
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # 1. Install system dependencies
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev wget

      # 2. Install TA-Lib from source
      - name: Install TA-Lib
        run: |
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xvzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib
          ./configure --prefix=/usr
          make
          sudo make install
          cd ..

      # 3. Set up Python and bot dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python packages
        run: |
          pip install -r requirements.txt

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: python bot.py
